FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY api_layer/ ./api_layer/
COPY ml_core/ ./ml_core/
COPY analytics/ ./analytics/

# Expose port
EXPOSE 8000

CMD ["uvicorn", "api_layer.main:app", "--host", "0.0.0.0", "--port", "8000"]
